---
 - hosts: all
   remote_user: portaone
   become: yes
   gather_facts: no
   tasks:


   - name: Update repositories cache and install "libqt4-scripttools" package
     apt:
       name: libqt4-scripttools
