---
 - hosts: all
   remote_user: student
   gather_facts: no 
   vars:
     ansible_ssh_private_key_file: "/home/alf/.ssh/porta73student"
   tasks:
   - name: Run some command
     command: wget http://ftp.us.debian.org/debian/pool/main/libp/libpng/libpng12-0_1.2.50-2+deb8u3_amd64.deb -O /home/student/libpng12-0_1.2.50-2+deb8u3_amd64.deb
     become: no
     
