---
 - hosts: all
   remote_user: portaone
   become: yes
   gather_facts: no
   tasks:
 
 
   - lineinfile:
       path: /etc/hosts
       line: '127.0.0.1 netacad.com www.netacad.com www.google-analytics.com'
