#!/usr/bin/python3


import json
import sys
import os
import subprocess


def build_cmd(request):
    inventory = request.get('inventory', '')
    playbook = request.get('playbook', '')
    extra_vars = request.get('extra_vars', dict())
    cmd = 'ansible-playbook playbooks/{} -i hosts'.format(playbook)
    options = []
    for arg in extra_vars:
        options.append('{}="{}"'.format(arg, extra_vars[arg]))
    join = ' '.join(options)
    if len(join) != 0:
        cmd = "{} -e '{}'".format(cmd, join)
    return cmd


def main():
    request = json.loads(input())
    cmd = build_cmd(request)
    ansible = subprocess.Popen(cmd, shell=True, executable='/bin/bash', stdout=subprocess.PIPE, stderr=subprocess.STDOUT, cwd=os.path.join(os.getcwd(), 'ansible'))
    while True:
        line = ansible.stdout.readline()
        if not line:
            break
        print(json.dumps({'line': line.decode()}))
    rc = ansible.poll()
    print(json.dumps({'code': rc}))


if __name__ == "__main__":
    main()
